# Generated by Django 5.1.1 on 2024-10-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybervaultapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='platform',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='pass_vault',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='username_vault',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
